#指定kafka服务地址
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.2.79:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #key编码方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  #消息体编码方式
