spring:
  application:
    name: dm-gateway-zuul
server:
  port: 7600
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
zuul:
  #路由参数
  routes:
    #对所有/user/前缀访问dm-user-consumer
    dm-user-consumer: /user/**  #userlogin -> /user/userlogin
    #dm-xxxx-service: /xxxx/**

    #关闭过滤器
    Secondfilter:
      pre:
        disable: true
