spring:
  application:
    name: dm-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/applepip/springcloud-config-demo.git
          search-paths: config-file
server:
  port: 7900
